---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'

rules:
  no-console: 0
